### ISSUE TITLE
Increase usability of `Real` trait

### ISSUE THREAD

**Issue by tolvanea** [Axect/Peroxide#10]
This is not a bug, but just rather feature request for some future version. As far as I understand, this feature would be a breaking change, so understandably the necessity of this request should be considered. (I am also a newbie, so I may think things wrong too.)

`Real` trait is sweet, because functions can be made generic over type, and the function can be easily passed to automatic differentiation. Now in my case the `Real` type is practically `f64` or `Number`. However, many numeric traits that are implemented for `Number`, are not trait bounds on `Real`. For example `Neg` and  `PartialOrd ` are missing.

Also, binary operands `f:f64` and `r: Real` can be written only as `r @ f` but not `f @ r`, where @ is one of operators {+, -, *, /}. This also makes function writing a bit more cumbersome.

This is probably a breaking change, because it may be technically possible that somebody have implemented `Real` for some own type. (So should `Real` be also locked, so that it can not be implemented outside the crate?)

**Comment by Axect** [comment]
So great suggestions!
I've been thinking a lot about it either. `Real` is obviously good trait, but it has a problem.
`Real` is associated type trait. It means we can use `Real` trait as type traits of input variables, but we can't use it as return type alone. (We should annotates type)
By this problem, it is difficult to write `Real -> Real` functions. It's possible only if two `Real`s have same type signatures. But for `Number` it has no problems for it. (Of course, to write function of `Number` always requires three implementations - `f64`, `Dual`, `HyperDual`. This makes us uncomfortable)

I also want to increase usability of `Real` trait. Thus, more considerations should be required.
And also, I had a concerns - `Real` & `Number` have similar roles. So, there are following options.

1. Remove `Real` -> Only use `Number`
2. Remove `Number` -> Only use `Real`
3. Define proper criterion to separate their roles (Use `Number` & `Real` both)

I would like to hear your opinion on this.

**Comment by tolvanea** [comment]
Oh yeah, now I understand, didn't think of that at all.  
(I just thought as an analogy that ndarray-scalar operation can be ordered in both ways, but that works because ndarray is not scalar.)

Now I also understand why Number exists (instead of just Dual). Real-trait is still quite usable, even though it requires minor modifications to the original function. 

Thanks for clarification!
