### ISSUE TITLE
`cargo build --examples` does not appear to build the examples

### ISSUE THREAD

**Issue by davidssmith** [Axect/Peroxide#12]

**Comment by Axect** [comment]
Hmm.. The `example` directory contains just code.
Maybe build whole examples are not efficient so I'm working on make another example repository - [Peroxide Gallery](https://github.com/Axect/Peroxide_Gallery)

**Comment by disDeal** [comment]
You can rename the example folder as examples and everything will work fine.

**Comment by Axect** [comment]
Yes, if rename `example` folder to `examples` then we 'can' try build.
But, codes in that directory require various features & various data.
And some codes are deprecated.

Of course if you want to use `cargo build --examples` though, then I'll remove legacy codes in that directory.

**Comment by Axect** [comment]
I did. You can do `cargo run --examples --all-features`. (But not recommended)
