### ISSUE TITLE
The `rng` for various distributions should use those from `rand_distr` crate

### ISSUE THREAD

**Issue by lebensterben** [Axect/Peroxide#13]
[rand_distr](https://docs.rs/rand_distr/0.2.2/rand_distr/) crate contains `rng` functions we need, and they use more efficient algorithms then we currently have.

So consider making thin wrapper functions instead of writing our own `rng` instead.

**Comment by Axect** [comment]
Good idea!
I'll apply this idea soon.

**Comment by Axect** [comment]
I did this to current distributions. For more distributions, I will apply later.
