### ISSUE TITLE
Invalid Certificate for peroxide.info

### ISSUE THREAD

**Issue by schrieveslaach** [Axect/Peroxide#15]
The crate's doc page is not secure due to none matching CN name (valid only for *.surge.sh).

![image](https://user-images.githubusercontent.com/16558417/75320746-a9b44800-586f-11ea-9725-356c9abaa9a0.png)

**Comment by Axect** [comment]
Yes. I recognized it.

Now, I change main domain to [https://peroxide.surge.sh](https://peroxide.surge.sh)
And use [https://peroxide.info](https://peroxide.info) to redirection domain.

**Comment by schrieveslaach** [comment]
Cool, now it works.
