### ISSUE TITLE
Taylor mode automatic differentiation

### ISSUE THREAD

**Issue by Axect** [Axect/Peroxide#22]
`Peroxide` has two AD methods - `Dual`, `HyperDual`. But these are only 1st and 2nd order methods, and they are distinct. So, we need not only higher order AD but also generic.

- [x] Struct `AD`
  - [x] `fmt::Display`
  - [x] `Copy`?
  - [x] `From<T>`
- [x] `std::ops` for `AD`
  - [x] `Add`, `Sub`, `Neg`
  - [x] `Mul`
  - [x] `Div`
- [x] `PowOps` for `AD`
  - [x] `powi`
  - [x] `powf`
  - [x] `pow`
- [x] `TrigOps` for `AD`
  - [x] `sin`, `cos`, `tan`
  - [x] `asin`, `acos`, `atan`
  - [x] `sinh`, `cosh`, `tanh`
  - [x] `asinh`, `acosh`, `atanh`
  - [x] `sin_cos`, `sinh_cosh`
- [x] `ExpLogOps` for `AD`
  - [x] `exp`, `ln`
  - [x] `log`, `log2`, `log10`
- [x] `std::ops` with `f64`
	- [x] `Add`, `Sub`
	- [x] `Mul`, `Div`
- [x] Change the structure - `proc_macro` to `Enum` (to reduce compile time)
- [x] Generic AD function - `ADFn`
- [x] Apply to numerical things
	- [x] `numerical/root`
	- [x] `numerical/ode`
	- [x] `numerical/optimize`
	- [x] `numerical/utils`

**Comment by nixar0x0** [comment]
Hi, am interested in your library. Can you make some todo task so we can we pick that if we want to contribute?

**Comment by tbmreza** [comment]
@nixar0x0 You could pick up anything from https://github.com/Axect/Peroxide/blob/master/TODO.md and have your pull request reviewed almost right away (judging from https://github.com/Axect/Peroxide/pulls?q=is%3Apr+is%3Aclosed ).

**Comment by Axect** [comment]
@nixar0x0 Thank you for interests and @tbmreza thank you for good advice.
I'll update TODO.md more specifically soon.
