### ISSUE TITLE
Uniform random generator behaviour

### ISSUE THREAD

**Issue by spar7453** [Axect/Peroxide#23]
I am not sure whether it is intended or not but

Uniform(0,1) has type TPDist<i32> and
Uniform(0,1).sample(10) type generates random integers between [0, 1), so only zeros

However,
Normal(0,1) has the same type TPDist<i32> and
Nomral(0,1).sample(10) genrates random floats from the distribution

**Comment by Axect** [comment]
Hello,

`Uniform(T, T).sample(n)` returns `T` types vector which has length `n`.
So, if you want to generate float uniform random array then use `Uniform(0f64, 1f64)` instead.
(Documentation is not updated. I'll update documentation asap.)

But for `Normal`, we don't expect integer or unsigned integer samples. Thus, for `Normal` only float type samples are allowed.

**Comment by spar7453** [comment]
thank you
