### ISSUE TITLE
Add support of root-finding

### ISSUE THREAD

**Issue by schrieveslaach** [Axect/Peroxide#25]
I use Peroxide for some number cruching. For example, my code interpolates a measurement series of an analogue-digital converter with a spline and it analyzes the first and second derivatives. Therefore, I need to find the root of these derivatives.

However, there is no bisection or any other numerical root-find method in Peroxide and I have to use the `rootfind` crate but this crate is not actively maintained. Additionally, if root finding is provided by Peroxide, this would reduce the number of crate in my dependencies.

**Comment by Axect** [comment]
Good suggestion!
There is a newton method in peroxide, but it's not user-friendly. (I used it to solve implicit ODE only.) So, one day I wanted to implement root finding algorithm, and now seems to be the right time.

I plan to implement the following algorithms.

- [ ] Bisection
- [ ] Secant
- [ ] Newton-Raphson
- [ ] False position (Regular falsi)

And maybe following algorithms can be added.

- [ ] Bairstow method (for Polynomial)
- [ ] Illinois algorithm
- [ ] Anderson–Björck algorithm

Are there anything else you need?

**Comment by schrieveslaach** [comment]
Cool, if you need any help regarding testing or ergonomics of the API, please let me know.

**Comment by Axect** [comment]
@schrieveslaach I implemented Bisection, Secant, Newton, False Position methods via automatic differentiations and published ver 0.25.3.
You can see the explanations in [peroxide docs](https://peroxide.surge.sh/numerical/root/index.html).

Root finding methods are implemented in two ways - Low-level, High-level.
* Low-level is more difficult to use (should annotate specific AD type), but it can check condition number & see step-wise update.
* High-level is more convenient to use (need not annotate any type), but it can't check internal iterations.

If you have any suggestions or questions, please let me know.
