### ISSUE TITLE
Jacobian by automatic differentiation of multi variable function

### ISSUE THREAD

**Issue by russellb23** [Axect/Peroxide#3]
Thanks for this wonderful library mate,

Could anyone post an example for Jacobian for multi-variable function? Ex:

`f(x;t) = x1 * exp(x2*t)`

Thanks

**Comment by Axect** [comment]
Thanks for your interests.
I wrote code for your example function.

```rust
extern crate peroxide;
use peroxide::*;

fn main() {
    // t=1, x1=2, x2=3
    let x0 = c!(1, 2, 3);

    // jacobian at t=1, x1=2, x2=3
    jacobian(x0, f).print();
}

fn f(xs: Vec<Dual>) -> Vec<Dual> {
    let t = xs[0];
    let x1 = xs[1];
    let x2 = xs[2];

    vec![x1 * (x2 * t).exp()]
}
```

Then you can see the result:

```sh
   Compiling peroxide v0.9.4 (/home/kavis/Documents/Project/Rust_Project/Peroxide)
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
     Running `target/debug/jacobian`
          c[0]     c[1]     c[2]
 r[0] 120.5132  20.0855  40.1711
```

This result is exactly matched the symbolic result  at `t=1, x1=2, x2=3`:

```sh
[(x1*x2*exp(t*x2), e^(t*x2),  t*x1*e^(t*x2)]
```

The function `jacobian` in `numerical/utils` is in test-stage. So, the shape of `jacobian` is weird.

Maybe I'll change whole shape of functions & structures in `numerical` soon. (and I will endeavor to complete the `peroxide gitbook`)
If you have any suggestions, please do so at anytime.  

Thanks.

**Comment by russellb23** [comment]
Thanks mate
