### ISSUE TITLE
Blas linkage

### ISSUE THREAD

**Issue by gfaster** [Axect/Peroxide#54]
As it stands now, Peroxide enforces use of OpenBLAS even though all the libraries and apis it uses are agnostic to the BLAS library variant. In order to use a different BLAS implementation, one must delete Peroxide's `build.rs`, everything works fine otherwise. Especially as [this tutorial page](https://github.com/Axect/Issues/tree/f90ddbd3dbebbff3cf711ec9a2042aa43e471e51/Rust) is linked in the README, I think it should be expected that the user should be the one to include the linkage lines in their `build.rs`.

Realistically, I think there are a few good ways of changing this:
1. Just remove Peroxide's `build.rs`and leave it to the user to include the right libraries (I believe this is the best course of action)
2. Add a "no explicit linkage" feature that disables Peroxide's `build.rs`
3. Change the linkage from `openblas` to `blas` - many distros/package managers will have `libblas` symlinked to the installed BLAS implementation, OpenBLAS included.
4. Add `links` tag to Cargo.toml to allow for explicit overriding

Regardless, Peroxide explicitly linking to OpenBLAS is undesirable due to the plethora of other BLAS implementations (including open source ones like ClBlast) that can be used with no source code changes.

**Comment by gfaster** [comment]
Reading [Cargo book](https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages) and it seems like convention dictates `build.rs` should *not* link to any system libraries as it already depends on `blas` which in turn depends on `blas-sys`. `blas-sys`, according to Cargo convention, would be the package to link to the native library. However, as [this issue](https://github.com/blas-lapack-rs/blas-sys/issues/17) shows, it's not nearly that simple.

From this, I would conclude that Peroxide should definitely *not* include any linkage in `build.rs`, but as `blas-sys` does not link as it should by convention, it should be left to the end user to link but continue manually linking for development.

**Comment by Axect** [comment]
@gfaster Thank you for great feedback!
I totally agree with your suggestion to remove the linkage and leave it to the user to include the appropriate BLAS implementations in their `build.rs`.  I had implemented it a while back for people unfamiliar with Rust and the BLAS ecosystem (I wasn't familiar with it at the time either), but I haven't gotten around to fixing it since :disappointed:.

Thank you again for reporting this issue. I'll fix this problem and publish new version soon :rocket:

**Comment by Axect** [comment]
I've released Ver 0.33.0 with your feedback and updated the BLAS description in the README accordingly. You should now be able to use the BLAS backend of your choice.
