### ISSUE TITLE
Inconsistent naming of Lambert W functions

### ISSUE THREAD

**Issue by JSorngard** [Axect/Peroxide#65]
I just realized that I named the Lambert W functions inconsistently in the `prelude` implementation: the secondary branch was given the name `lambert_w_m1` when it's named `lambert_wm1` in `fuga`. 

The fix is easy, just rename the function to `lambert_wm1` in `prelude`, but this would be a breaking change.

It's probably not worth worrying about as the API is different between the `prelude` and `fuga` implementations anyway, but I wanted to notify you.

**Comment by Axect** [comment]
Oh, I got it. Thank you for notice.
I'll fix it soon.

**Comment by Axect** [comment]
Thanks again for bringing this to our attention.
The issue has been fixed and published in version 0.37.9.
You can check the details in the latest release: [v0.37.9](https://github.com/Axect/Peroxide/releases/tag/v0.37.9)
