### ISSUE TITLE
Add default MATLAB linspace method macro behavior

### ISSUE THREAD

**Issue by tarolling** [Axect/Peroxide#84]
[there are two signatures](https://www.mathworks.com/help/matlab/ref/double.linspace.html) of the `linspace` MATLAB method, which generates 100 points by default. if this is something that could be useful to people, i can go ahead and help implement the new syntax rule.

**Comment by Axect** [comment]
Hello @tarolling 
Thanks for your patience - apologies for the delayed response!

Your idea about supporting both signatures of the linspace MATLAB method with the 100-point default seems reasonable. If you'd be willing to implement this new syntax rule, I'd be happy to review and merge it right away.

Let me know if you need any clarification or run into questions during the implementation.
