### ISSUE TITLE
Documentation search results does not work

### ISSUE THREAD

**Issue by tolvanea** [Axect/Peroxide#9]
If one goes to the documentation, searches something, and clicks some search result, then "page not found" -page comes up.

For example, clicking any search result on following site gives "page not found"-error:
http://peroxide.info/?search=matrix

**Comment by Axect** [comment]
Thank you for interests.
Now, I updated documentation server, and searching works well in my case.
If you have same problems too, then please let me know.

**Comment by Axect** [comment]
Ah, I misunderstood your issues. That is caused from separation of documents & source codes.
I already recognized that problems but it was too busy to fix it.
I will fix this error soon.
Thanks.

**Comment by Axect** [comment]
I fixed.
If you still have any problems, then please let met know.

**Comment by tolvanea** [comment]
Thank ya!
